apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgserver
  namespace: imgbot
  labels:
    name: imgserver
spec:
  selector:
    matchLabels:
      app: imgserver
  replicas: 5
  template:
    metadata:
      labels:
        app: imgserver
    spec:
      containers:
        - name: imgserver
          image: ghcr.io/rwilliaise/imgbot-server:latest
          resources:
            limits:
              cpu: "0.5"
              memory: "500Mi"
            requests:
              cpu: "0.25"
              memory: "50Mi"
          ports:
            - containerPort: 8080