apiVersion: apps/v1
kind: Deployment
metadata:
  name: img-bot
spec:
  selector:
    matchLabels:
      app: img-bot
  replicas: 1
  template:
    metadata:
      labels:
        app: img-bot
    spec:
      containers:
        - name: img-bot
          image: ghcr.io/rwilliaise/imgbot:latest
          resources:
            limits:
              cpu: "0.5"
              memory: "500Mi"
            requests:
              cpu: "0.25"
              memory: "50Mi"
          env:
            - name: IMGBOT_DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: imgbot-secret
                  key: token
            - name: IMGBOT_DISCORD_APPID
              valueFrom:
                secretKeyRef:
                  name: imgbot-secret
                  key: appid