apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgbot
  namespace: imgbot
  labels:
    name: imgbot
spec:
  selector:
    matchLabels:
      app: imgbot
  replicas: 1
  template:
    metadata:
      labels:
        app: imgbot
    spec:
      containers:
        - name: imgbot
          image: ghcr.io/rwilliaise/imgbot:latest
          resources:
            limits:
              cpu: "0.5"
              memory: "500Mi"
            requests:
              cpu: "0.25"
              memory: "50Mi"
          env:
            - name: IMGBOT_DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: imgbot-secret
                  key: token
            - name: IMGBOT_DISCORD_APPID
              valueFrom:
                secretKeyRef:
                  name: imgbot-secret
                  key: appid