apiVersion: v1
kind: Namespace
metadata:
  name: imgbot

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgserver
  namespace: imgbot
  labels:
    name: imgserver
spec:
  selector:
    matchLabels:
      app: imgserver
  replicas: 5
  template:
    metadata:
      labels:
        app: imgserver
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: imgserver
          image: ghcr.io/rwilliaise/imgbot-server:latest
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: "0.5"
              memory: "500Mi"
            requests:
              cpu: "0.25"
              memory: "50Mi"
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: imgserver
  namespace: imgbot
  labels:
    name: imgserver
spec:
  selector:
    app: imgserver
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgbot
  namespace: imgbot
  labels:
    name: imgbot
spec:
  selector:
    matchLabels:
      app: imgbot
  replicas: 1
  template:
    metadata:
      labels:
        app: imgbot
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: imgbot
          image: ghcr.io/rwilliaise/imgbot:latest
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: "0.5"
              memory: "500Mi"
            requests:
              cpu: "0.25"
              memory: "50Mi"
          env:
            - name: IMGBOT_TENOR_APIKEY
              valueFrom:
                secretKeyRef:
                  name: imgbot-secret-tenor
                  key: apikey
            - name: IMGBOT_DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: imgbot-secret
                  key: token
            - name: IMGBOT_DISCORD_APPID
              valueFrom:
                secretKeyRef:
                  name: imgbot-secret
                  key: appid