apiVersion: v1
kind: Service
metadata:
  name: imgserver
  namespace: imgbot
  labels:
    name: imgserver
spec:
  selector:
    app: imgserver
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080