[package]
name = "img_server"
version = "0.1.2"
authors = ["rwilliaise"]
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "img_server"
path = "main.rs"

[dependencies]
actix-web = "4.0.0-beta.21"
actix-rt = "2.6.0"
