[package]
name = "img_server"
version = "0.1.0"
authors = ["rwilliaise"]
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "img_server"
path = "main.rs"

[dependencies]
