[package]
name = "imgBot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "img_bot"
path = "main.rs"

[dependencies]
serenity = "0.10.10"
